/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FEED_PB_H_INCLUDED
#define PB_FEED_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PriceChange {
    double value;
    double percentage;
} PriceChange;

typedef struct _StockData {
    char symbol[16];
    double lastprice;
    double volume;
    double high;
    double low;
    double open;
    double frequency;
    double foreignbuy;
    double foreignsell;
    double average;
    char date[40];
    double close;
    double previous;
    double value;
    bool has_change;
    PriceChange change;
} StockData;

typedef struct _StockFeed {
    bool has_stock_data;
    StockData stock_data;
} StockFeed;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define StockFeed_init_default                   {false, StockData_init_default}
#define StockData_init_default                   {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, false, PriceChange_init_default}
#define PriceChange_init_default                 {0, 0}
#define StockFeed_init_zero                      {false, StockData_init_zero}
#define StockData_init_zero                      {"", 0, 0, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, false, PriceChange_init_zero}
#define PriceChange_init_zero                    {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PriceChange_value_tag                    1
#define PriceChange_percentage_tag               2
#define StockData_symbol_tag                     1
#define StockData_lastprice_tag                  2
#define StockData_volume_tag                     3
#define StockData_high_tag                       4
#define StockData_low_tag                        5
#define StockData_open_tag                       6
#define StockData_frequency_tag                  7
#define StockData_foreignbuy_tag                 8
#define StockData_foreignsell_tag                9
#define StockData_average_tag                    10
#define StockData_date_tag                       11
#define StockData_close_tag                      12
#define StockData_previous_tag                   13
#define StockData_value_tag                      14
#define StockData_change_tag                     15
#define StockFeed_stock_data_tag                 9

/* Struct field encoding specification for nanopb */
#define StockFeed_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stock_data,        9)
#define StockFeed_CALLBACK NULL
#define StockFeed_DEFAULT NULL
#define StockFeed_stock_data_MSGTYPE StockData

#define StockData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   symbol,            1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lastprice,         2) \
X(a, STATIC,   SINGULAR, DOUBLE,   volume,            3) \
X(a, STATIC,   SINGULAR, DOUBLE,   high,              4) \
X(a, STATIC,   SINGULAR, DOUBLE,   low,               5) \
X(a, STATIC,   SINGULAR, DOUBLE,   open,              6) \
X(a, STATIC,   SINGULAR, DOUBLE,   frequency,         7) \
X(a, STATIC,   SINGULAR, DOUBLE,   foreignbuy,        8) \
X(a, STATIC,   SINGULAR, DOUBLE,   foreignsell,       9) \
X(a, STATIC,   SINGULAR, DOUBLE,   average,          10) \
X(a, STATIC,   SINGULAR, STRING,   date,             11) \
X(a, STATIC,   SINGULAR, DOUBLE,   close,            12) \
X(a, STATIC,   SINGULAR, DOUBLE,   previous,         13) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,            14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  change,           15)
#define StockData_CALLBACK NULL
#define StockData_DEFAULT NULL
#define StockData_change_MSGTYPE PriceChange

#define PriceChange_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   value,             1) \
X(a, STATIC,   SINGULAR, DOUBLE,   percentage,        2)
#define PriceChange_CALLBACK NULL
#define PriceChange_DEFAULT NULL

extern const pb_msgdesc_t StockFeed_msg;
extern const pb_msgdesc_t StockData_msg;
extern const pb_msgdesc_t PriceChange_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StockFeed_fields &StockFeed_msg
#define StockData_fields &StockData_msg
#define PriceChange_fields &PriceChange_msg

/* Maximum encoded size of messages (where known) */
#define FEED_PB_H_MAX_SIZE                       StockFeed_size
#define PriceChange_size                         18
#define StockData_size                           186
#define StockFeed_size                           189

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
