/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_HANDSHAKE_PB_H_INCLUDED
#define PB_HANDSHAKE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Handshake {
    char userId[32];
    char key[128];
} Handshake;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Handshake_init_default                   {"", ""}
#define Handshake_init_zero                      {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define Handshake_userId_tag                     1
#define Handshake_key_tag                        3

/* Struct field encoding specification for nanopb */
#define Handshake_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   userId,            1) \
X(a, STATIC,   SINGULAR, STRING,   key,               3)
#define Handshake_CALLBACK NULL
#define Handshake_DEFAULT NULL

extern const pb_msgdesc_t Handshake_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Handshake_fields &Handshake_msg

/* Maximum encoded size of messages (where known) */
#define HANDSHAKE_PB_H_MAX_SIZE                  Handshake_size
#define Handshake_size                           163

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
