/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ORDERBOOK_REQ_PB_H_INCLUDED
#define PB_ORDERBOOK_REQ_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Orderbook {
    pb_size_t orderbook_count;
    char orderbook[5][16];
    pb_size_t livequote_count;
    char livequote[5][16]; /* daftar simbol yang akan disubscribe */
} Orderbook;

typedef struct _OrderbookSubscribe {
    char userId[32]; /* ID pengguna */
    bool has_subs;
    Orderbook subs; /* daftar livequote */
    char key[128]; /* wskey */
} OrderbookSubscribe;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Orderbook_init_default                   {0, {"", "", "", "", ""}, 0, {"", "", "", "", ""}}
#define OrderbookSubscribe_init_default          {"", false, Orderbook_init_default, ""}
#define Orderbook_init_zero                      {0, {"", "", "", "", ""}, 0, {"", "", "", "", ""}}
#define OrderbookSubscribe_init_zero             {"", false, Orderbook_init_zero, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Orderbook_orderbook_tag                  2
#define Orderbook_livequote_tag                  6
#define OrderbookSubscribe_userId_tag            1
#define OrderbookSubscribe_subs_tag              2
#define OrderbookSubscribe_key_tag               3

/* Struct field encoding specification for nanopb */
#define Orderbook_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   orderbook,         2) \
X(a, STATIC,   REPEATED, STRING,   livequote,         6)
#define Orderbook_CALLBACK NULL
#define Orderbook_DEFAULT NULL

#define OrderbookSubscribe_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   userId,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  subs,              2) \
X(a, STATIC,   SINGULAR, STRING,   key,               3)
#define OrderbookSubscribe_CALLBACK NULL
#define OrderbookSubscribe_DEFAULT NULL
#define OrderbookSubscribe_subs_MSGTYPE Orderbook

extern const pb_msgdesc_t Orderbook_msg;
extern const pb_msgdesc_t OrderbookSubscribe_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Orderbook_fields &Orderbook_msg
#define OrderbookSubscribe_fields &OrderbookSubscribe_msg

/* Maximum encoded size of messages (where known) */
#define ORDERBOOK_REQ_PB_H_MAX_SIZE              OrderbookSubscribe_size
#define OrderbookSubscribe_size                  336
#define Orderbook_size                           170

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
