/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "orderbook_req.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LiveFeedSub, LiveFeedSub, AUTO)


PB_BIND(SymbolSubscribe, SymbolSubscribe, 2)



