/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "orderbook_resp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StockOrderbook, StockOrderbook, 4)


PB_BIND(StockOrderbook_Orderbook, StockOrderbook_Orderbook, 4)



