/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ORDERBOOK_RESP_PB_H_INCLUDED
#define PB_ORDERBOOK_RESP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _StockOrderbook_Orderbook {
    char symbol[16];
    char body[4096];
    int32_t sequenceNumber;
    int32_t orderbookId;
    char datetime[64];
    int32_t bookType;
} StockOrderbook_Orderbook;

typedef struct _StockOrderbook {
    bool has_data;
    StockOrderbook_Orderbook data;
} StockOrderbook;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define StockOrderbook_init_default              {false, StockOrderbook_Orderbook_init_default}
#define StockOrderbook_Orderbook_init_default    {"", "", 0, 0, "", 0}
#define StockOrderbook_init_zero                 {false, StockOrderbook_Orderbook_init_zero}
#define StockOrderbook_Orderbook_init_zero       {"", "", 0, 0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define StockOrderbook_Orderbook_symbol_tag      1
#define StockOrderbook_Orderbook_body_tag        2
#define StockOrderbook_Orderbook_sequenceNumber_tag 3
#define StockOrderbook_Orderbook_orderbookId_tag 4
#define StockOrderbook_Orderbook_datetime_tag    5
#define StockOrderbook_Orderbook_bookType_tag    8
#define StockOrderbook_data_tag                  10

/* Struct field encoding specification for nanopb */
#define StockOrderbook_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,             10)
#define StockOrderbook_CALLBACK NULL
#define StockOrderbook_DEFAULT NULL
#define StockOrderbook_data_MSGTYPE StockOrderbook_Orderbook

#define StockOrderbook_Orderbook_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   symbol,            1) \
X(a, STATIC,   SINGULAR, STRING,   body,              2) \
X(a, STATIC,   SINGULAR, INT32,    sequenceNumber,    3) \
X(a, STATIC,   SINGULAR, INT32,    orderbookId,       4) \
X(a, STATIC,   SINGULAR, STRING,   datetime,          5) \
X(a, STATIC,   SINGULAR, INT32,    bookType,          8)
#define StockOrderbook_Orderbook_CALLBACK NULL
#define StockOrderbook_Orderbook_DEFAULT NULL

extern const pb_msgdesc_t StockOrderbook_msg;
extern const pb_msgdesc_t StockOrderbook_Orderbook_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StockOrderbook_fields &StockOrderbook_msg
#define StockOrderbook_Orderbook_fields &StockOrderbook_Orderbook_msg

/* Maximum encoded size of messages (where known) */
#define ORDERBOOK_RESP_PB_H_MAX_SIZE             StockOrderbook_size
#define StockOrderbook_Orderbook_size            4213
#define StockOrderbook_size                      4216

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
