/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PING_PB_H_INCLUDED
#define PB_PING_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Ping {
    char message[16];
} Ping;

typedef struct _WSWrapper {
    bool has_ping;
    Ping ping;
} WSWrapper;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Ping_init_default                        {""}
#define WSWrapper_init_default                   {false, Ping_init_default}
#define Ping_init_zero                           {""}
#define WSWrapper_init_zero                      {false, Ping_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Ping_message_tag                         1
#define WSWrapper_ping_tag                       4

/* Struct field encoding specification for nanopb */
#define Ping_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define Ping_CALLBACK NULL
#define Ping_DEFAULT NULL

#define WSWrapper_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping,              4)
#define WSWrapper_CALLBACK NULL
#define WSWrapper_DEFAULT NULL
#define WSWrapper_ping_MSGTYPE Ping

extern const pb_msgdesc_t Ping_msg;
extern const pb_msgdesc_t WSWrapper_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Ping_fields &Ping_msg
#define WSWrapper_fields &WSWrapper_msg

/* Maximum encoded size of messages (where known) */
#define PING_PB_H_MAX_SIZE                       WSWrapper_size
#define Ping_size                                17
#define WSWrapper_size                           19

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
