/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PONG_PB_H_INCLUDED
#define PB_PONG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Pong {
    char message[16];
} Pong;

typedef struct _PongReceive {
    bool has_pong;
    Pong pong;
} PongReceive;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Pong_init_default                        {""}
#define PongReceive_init_default                 {false, Pong_init_default}
#define Pong_init_zero                           {""}
#define PongReceive_init_zero                    {false, Pong_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Pong_message_tag                         1
#define PongReceive_pong_tag                     2

/* Struct field encoding specification for nanopb */
#define Pong_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define Pong_CALLBACK NULL
#define Pong_DEFAULT NULL

#define PongReceive_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pong,              2)
#define PongReceive_CALLBACK NULL
#define PongReceive_DEFAULT NULL
#define PongReceive_pong_MSGTYPE Pong

extern const pb_msgdesc_t Pong_msg;
extern const pb_msgdesc_t PongReceive_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Pong_fields &Pong_msg
#define PongReceive_fields &PongReceive_msg

/* Maximum encoded size of messages (where known) */
#define PONG_PB_H_MAX_SIZE                       PongReceive_size
#define PongReceive_size                         19
#define Pong_size                                17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
